name: Bunnyshell CI
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo Done
    outputs:
      foo: bar
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo Done
    needs: job1
  job2b:
    runs-on: ubuntu-latest
    steps: 
      - run: sleep 30 && echo Done
    needs: job1
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo Done
    needs: [job1,job2]
  job4:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo "Done ${{ needs.job1.outputs.foo }}"
    needs: [job2]
  job5:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo "Done ${{ needs.job1.outputs.foo }}"
        env:
          test: "${{ needs.job1.outputs.foo }}"
